{
  imports = [
    ./homepage
    ./gatus
    ./qbittorrent
    ./plex
    ./tautulli
    ./searxng
    ./factorio
    ./whoogle
    ./redlib
    ./home-assistant
    ./calibre
    ./ecowitt2mqtt
    ./maloja
    ./multi-scrobbler
    ./immich
    ./rxresume
    ./browserless
    ./overseer
    ./changedetection
    ./nextdns-exporter
    ./hs110-exporter
    ./linkding
    ./autobrr
    ./filebrowser
    ./maintainerr
    ./cross-seed
    ./redbot
  ];
}
