---
# go-task runner file
version: "3"

tasks:
  default:
    silent: true
    cmds:
      - task -l

  deploy:
    desc: Deploy app
    cmds:
      - bash -c "doppler run -p github -c prd_vaultwarden -- fly deploy"
