---
keys:
  - &nixosvm age1d3qtnwd73k0npgwhqwpwysdpqa2zyyjyyzs463f5rak9swmw45gsxdyjyn
  - &nixosvm2 age16mwx76r29pa9lnmagujw9adxrpujxmxu38hjfastf6pgw6v66gjs5ugewz

creation_rules:
  - path_regex: .*\.sops\.yaml$
    key_groups:
      - age:
          - *nixosvm
          - *nixosvm2
