{
  imports = [
    ./monitoring.nix
    ./reboot-required-check.nix
    ./podman
    ./nfs
    ./glances
    ./syncthing
    ./restic
    ./mosquitto
    ./zigbee2mqtt
    ./postgresql
    ./code-server
    ./grafana
    ./radicale
    ./node-red
    ./nginx
    ./miniflux
    ./rss-bridge
    ./paperless
    ./redis
    ./recyclarr
    ./sonarr
    ./radarr
    ./sabnzbd
    ./minio
    ./thelounge
    ./victoriametrics
    ./unpoller
    ./readarr
    ./lidarr
    ./prowlarr
    ./mariadb
    ./code-server
    ./navidrome
    ./atuin
    ./tandoor
    ./open-webui
    ./ntfy-sh
    ./trilium
    ./seafile
    ./firefly-iii
    ./rapt2mqtt
    ./technitium
    ./jellyfin
    ./minecraft-bedrock
    ./jellyseer
    ./glance
    ./qui
    ./satisfactory
  ];
}
