{
  imports = [
    ./monitoring.nix
    ./reboot-required-check.nix
    ./cloudflare-dyndns
    ./maddy
    ./dnscrypt-proxy2
    ./cockpit
    ./podman
    ./traefik
    ./nfs
    ./nix-serve
    ./glances
    ./syncthing
    ./restic
    ./powerdns
    ./adguardhome
    ./mosquitto
    ./zigbee2mqtt
    ./postgresql
    ./blocky
    ./code-server
    ./grafana
    ./radicale
    ./node-red
    ./nginx
    ./miniflux
    ./calibre-web
    ./rss-bridge
    ./paperless
    ./redis
    ./recyclarr
    ./sonarr
    ./radarr
    ./sabnzbd
    ./minio
    ./invidious
    ./thelounge
    ./victoriametrics
    ./unpoller
    ./readarr
    ./lidarr
    ./prowlarr
    ./mariadb
    ./code-server
    ./navidrome
    ./vikunja
    ./steam
    ./atuin
    ./silverbullet
    ./tandoor
    ./open-webui
  ];
}
