{
  lib,
  config,
  pkgs,
  ...
}:
with lib;
let
  resticBackups = config.services.restic.backups or { };
  backupNames = builtins.attrNames resticBackups;

  # Extract local and remote backups
  localBackups = builtins.filter (name: lib.hasSuffix "-local" name) backupNames;
  remoteBackups = builtins.filter (name: lib.hasSuffix "-remote" name) backupNames;

  # Generate the complete Justfile content
  justfileContent = ''
    # Restic backup tasks
    # Auto-generated by NixOS configuration
    # Do not edit manually - changes will be overwritten

    default:
        @just --list

    backup-local:
        #!/usr/bin/env bash
        set -euo pipefail
        sudo restic_nightly_snapshot.service
    ${
      if localBackups != [ ] then
        lib.concatMapStrings (
          name: "    sudo systemctl start restic-backups-${name}.service\n"
        ) localBackups
      else
        "    echo 'No local backups configured'\n"
    }

    backup-remote:
        #!/usr/bin/env bash
        set -euo pipefail
    ${
      if remoteBackups != [ ] then
        lib.concatMapStrings (
          name: "    sudo systemctl start restic-backups-${name}.service\n"
        ) remoteBackups
      else
        "    echo 'No remote backups configured'\n"
    }

    backup-all:
    ${
      if localBackups != [ ] || remoteBackups != [ ] then
        lib.concatStringsSep "" (
          lib.optional (localBackups != [ ]) "    just backup-local\n"
          ++ lib.optional (remoteBackups != [ ]) "    just backup-remote\n"
        )
      else
        "    @echo 'No backups configured'\n"
    }

  '';

  justfilePath = "/home/truxnell/Justfile";
  justfileSource = pkgs.writeText "restic-backup-justfile" justfileContent;
in
{
  config = mkIf (backupNames != [ ]) {

    # Deploy Justfile during system activation
    system.activationScripts.restic-justfile = ''
      mkdir -p $(dirname ${justfilePath})
      cp ${justfileSource} ${justfilePath}
      chown truxnell:users ${justfilePath}
      chmod 0644 ${justfilePath}
    '';
  };
}
