---
system:
    services:
        # apiTokenFile is just env vars for the service, hijack this to hide domains
        traefik:
            apiTokenFile: |
                CLOUDFLARE_API_KEY=b7e89056905c569e0f38c3ae37c9125dfdbce
                CLOUDFLARE_EMAIL=admin@voltaicforge.com
