system:
    services:
        #ENC[AES256_GCM,data:aViKoZKsnOLH1qIXEQUQ3YcUPYyXtm8n/g5vXivkCnKd09sJfCgcd7EsNJH0uTcJkzUKlXQ1aA2TalIKlTA08kcKJd5jIAbZHNgPQA==,iv:DBxhSvZh+2FH9CsfB1xWkZPS6W7nydW0gtVTH8pUFYQ=,tag:ujnyow8Vt92NxJ5s7bpu0Q==,type:comment]
        traefik:
            apiTokenFile: ENC[AES256_GCM,data:nxnLvF2tQDfHY+QuV6rabA7QcVj3/sATgDRw2UQ2IwGEzBPcLwL2h3DbJfiO+fwbCxlnac5QjpJ0SvWB42Dynn6V9ySW5jN4D3MPs+i7VemKLx95Es/nGqyEDXXvUW833g==,iv:LABgnbOV6GaWpiPSGyClMkkbBr72KxEme2ITLgKrTvA=,tag:LQpSAdW+DMvNsh1+JKWZmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lj5vmr02qkudvv2xedfj5tq8x93gllgpr6tzylwdlt7lud4tfv5qfqsd5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WE5MN2toRUorem1VM09O
            ZjAvRXN5Q29Pd1BOTmxTSlJNdkcrbWZkQ1JrClR1dEkwcGkwMWcyVmtMUkZ1cmpa
            eEtUL0ZaL0E3QklmdmdSMXErK0UzUFUKLS0tIG1YZFNJUk1qK0orNU5kN0JNV0Nr
            WnQ0YUVnckUvTEpaSlUvTzl4ZVBldE0KJnZdILPFe7/TtG2pMf/FYaf6Aj2xvjbb
            z8uo+vBHgYr/n9/we+WVe61B/Mo67GSA24LlFIFWwBbPbQ3TMzYUSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17edew3aahg3t5nte5g0a505sn96vnj8g8gqse8q06ccrrn2n3uysyshu2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOW9ra0xoZ2p3R0tNTUEx
            eXFCVkg2UlA2L3cvcTdwRndtZUhZOWdSVW1jCm1rYVJvVmx0V005YTV6eDcxc3pi
            dmt0dUs5a1ZqOGdLdERFMXFrSlhFSTgKLS0tIHJYOHM5N21Cc0JuNFJMMUZ6dVVr
            ajVBRHFneC84YXhpRyt0T3ZoSmV6RFEKyvkHawZbzhlGFvrzwdf42PljnBiVz15G
            0ulli+RDbBOZ5r4vdOHzV/ZhUdpnrkIC6RL2J7ZVNR+W8WY7ZxyEng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u4tht685sqg6dkmjyer96r93pl425u6353md6fphpd84jh3jwcusvm7mgk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZXc1K3ZlOEFXeUVCKzJp
            VWRKRGRPU3N2N3BpVGg3YnNzbDU2Q0ExSnp3CjJvWktTRzRERERyYTlHb2VqT2FP
            dWZhWmkwQTJweSs3ek9aSlhZZUtDQTgKLS0tIEtsV3d2ZWtDUis5MDhqSUI3c2My
            dkVURFFRZ0RyVXVnK0xpSlg0MEN0cjQKabFh5Mk4aqbA00MRWetkU037znRJojJr
            Dxy9yjYGtwXx0mg+BNypEwE6CIZc/xLOG3IhtLXX5I+CE5RQRE+k6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cp6vegrmqfkuj8nmt2u3z0sur7n0f7e9x9zmdv4zygp8j2pnucpsdkgagc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbzhWc0RTRGFpbEFHMGdR
            bnNJdnY1b2tQS2tYUVJKTjl1QVFNQUYyM0hZCjhZSkFuUjVPWXdtSlMwYlA3TXZu
            RUhkMDhybUpDNW00MVQzVUxuZUN3WDgKLS0tIGdKOWc3Y050SVhoNkd2bkJkUXo1
            NUg3endvRng0UDRIMVdCek8xM2xLRUkKaoB4b918vD0VEiChUmhMQPygjzGfET6p
            PImxh7iqLV9IcCsWMHGF8f6NFHHUWzA2WFU81qDDToMD+TofuhOJxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ekt5xz7u2xgdzgsrffhd9x22n80cn4thxd8zxjy2ey5vq3ca7gnqz25g5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc1Z6V3JMVGNQNUJNbExl
            RUU0aG9Yc2UxdGF4K1o3UmduQzlHWlUrakU4CnBPQUxiU2E4a0J2VWNLZDdFRGRq
            YjBHalZBSnlWL1hVcXJOZ0oycDJUeDgKLS0tIHNQNlFMQkdSZUdTSkRHckNOSG5H
            NXQrTFNNTkYwR3owWVRMMGVWZWk1K00KRq+heQ0aB9EDKrBeF0PjjLhuouhOWkhx
            5uhvwOy+LqRjO8rx7r9udamtp1ZGTedtnVgc5eTfpuv7lsJQUBlRqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jpeh4s553taxkyxhzlshzqjfrtvmmp5lw0hmpgn3mdnmgzku332qe082dl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZUt6RUtOSXpMdjVxdU5o
            Tk5xZER5eWdFRTRHdDRmcG9xRGR2SWNOamhRCmtUVEltUmJ2a2tQUUZsVnhBUStn
            eHU3WUpIMVNTVnZXNUtiaGtITmRIaVEKLS0tIGRWNXBRMGp1UFUwVS80VG51aFAx
            UW1Qc1R6U1JCdEJIbFVqWEFQcnl2TGsKzjqYibOguVYg9tYfQk80AepXrkVgC+L+
            6KHq+CE2XVuhlWUWsbb8pOvSwC8GLxxFLoOsf5zhiSSZuw841d8o8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j2r8mypw44uvqhfs53424h6fu2rkr5m7asl7rl3zn3xzva9m3dcqpa97gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YWMvMUpCYXJDWkVpZldI
            NDFXWGR6cmQ1d1JVZzdvMENRdWQ1NVhIZVNzClVHczdjWU1DR3hzQTAvR04xcVZP
            aFF6b0JhMlpKZC9RUnBRWURRT2loaFEKLS0tIDkyK1p1YWlQazRIZGlMWCtSMktk
            ejd4MEF1d09iSktJYXEzRUpoYUl3NEUKWlVcQXDKvwppTKfqQ6gA4I3aZycCxzRW
            kaOUYd9+rhyGia9tYAA1SmnSzb7zLrmdJG5wggPrsxdbOf7P6RnbJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezmtw7qaw93yggtcncqpyej9qjlref8au5uceqat49htmlfgps2swsttyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMFZZWkZSc0NQNjhmaDl0
            Zmp6bjRtNC9lWUhPNUtHc2t1T0tpVEZESVNnCkNmbk4yamFwckdTSWZxR2xGcnZH
            ME9wUE9YczFLYnZOQjBGSjRvRS9wOTgKLS0tIEI4OTJMRkZoYWpMYzV1aTBhaUZZ
            THBTbUl6SWxZbEZabkVLZ0ZkQTBHRGMKEKLJD/O/n7DSEnsDfVQcyDx9XoLODM1i
            SoXJH/0aqK3bQdaZhN3s33INvBeIQnFIR3L1akEFjGUVZq5DwkFzCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T22:40:59Z"
    mac: ENC[AES256_GCM,data:zL6jS725gBFL/Woqm2KvAz9m13R5KYipMKiCgHLW80zeofPdxe43J9NUFiUrsukHEGXD2xXYnL7bolmJEhpzM41u6YxzO5X37F8H+B6i8Tk52AR+HZK835geiamW8PBxJk/AS6M+vqpnBdCewY2ky6v8ajQH5Ijaw+MinJJbqIU=,iv:QU4Kh+dWFeBkz5QUFHSkbtX5VlsnYI57zZp1ZdDXpL4=,tag:PLxKb9ecC6QUmYtwvlMZxQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
