system:
    services:
        #ENC[AES256_GCM,data:uD5cecYw+jkC/qQvbBGcKmdN0ZxJAhwLSNm072nbhGLxgw+dNRIYLOiw3dICcbkQwZUBOs5MV3AiFHTaI8f3rHvOmsdLxLxPdT+t3w==,iv:a6DeVD2P3oHLeZc0pcRUJYfvledBQ0RkLXDw8rcG1Z4=,tag:Qzjihlp8P89RwEYb3egQUg==,type:comment]
        traefik:
            apiTokenFile: ENC[AES256_GCM,data:OmZq0fdHGvIj+WJmMW+H4zzoOTH5AD/kojx0GfZU9ZI0wR2xO7EyfpIPP2USvzhbwWlT7yVxZSPEr2jn1gqcNppSncyzZHr312qZmk2omtsn1UCQ7XdDKLBdjauNZcDnfw==,iv:e7odOnH2jtmh9BksRl/oxoe0VLIuPeBOZvXBkq+HNME=,tag:f20I3mzdgUf16l5Yef0bXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lj5vmr02qkudvv2xedfj5tq8x93gllgpr6tzylwdlt7lud4tfv5qfqsd5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZ1JSMUVCZWIvcEhuRDF1
            VHNrL2pQVUpKVFpxR01pMFJvZ1dZUFNGM1RjCjE5UTFOZXYrTU1odDRHYmJwdjJV
            ejJQOEdiYTBoc1RrdkpCKzNpdmkyQjQKLS0tIHQ2aVZyZmZsdFF1dzZ3NFNFYk1V
            UUx1VnhwMFVra3FQMWlMQWd3R2pkREUKbColBFMw8Ma76yMqp61MoCanc5DeMBaG
            R9K5DJV8EFHWWrx12QKOWl8XDugoUlvxw/Oq+WjrYEqdAx5pH80NZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17edew3aahg3t5nte5g0a505sn96vnj8g8gqse8q06ccrrn2n3uysyshu2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNWdNY3lPT0V1REJ2NW0v
            amhFY09OMkgrRTNlRDlTL2kwajVreEp6dG4wCnpVTmh5UCtManYwRHdxSHNMVVlM
            YjhKKzRkYm1EKzhhbHdtVWtyWXpQRjQKLS0tIDVKcXRiZGxBNFZUS1RPZXhKdENN
            ZlR2UWxWN09EeTQrR3M5U0U0RThyTWMKgYI6Xr55mjI9xBAyG+nYPWmPKGNMz2wP
            dnTDiaNxtxmE3tN/lkjgFOBuXIACLSo2yKwlmE/QnmHW8mi2Otlmqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u4tht685sqg6dkmjyer96r93pl425u6353md6fphpd84jh3jwcusvm7mgk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZTM0RlZudWV5bytnam9Q
            NnFmdGNqTzgvLy95QlhGQ1V3ZHRDUU5lNW5vCjVBQ0R1VWFkSVFEK3J5OWpzaDlu
            WnNZZUpjK2xLbnEzYytnTGYvaktJZWcKLS0tIGcva25XN2E0S0pwYjFRLzUrWE5T
            VDUyOGwrYjY4bndrTXozc0lBUDNxdG8Kz2EPBCfK0nN5tons7Po+/+A8cp7OYYPt
            boKNeCPbhSLT/er6RZh58638ngFzqgSr7aU+gvGusNwugRVczbb8hw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cp6vegrmqfkuj8nmt2u3z0sur7n0f7e9x9zmdv4zygp8j2pnucpsdkgagc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQkZ3YUNPU2Y5SkVBc1hS
            YXVqS1N5U3RYanF1d3ZKN0hNT3QycjA1T3lNCndvZ0dRYkRySUsxRVRjT0YycVB1
            b0lvWnNmV0hnY1JYeDBOeVRSTEs4UTQKLS0tIGFVL3M3SWxzTnFHdk5CWFBSTDhx
            eHhZTVN5Q2xCeS9UQ0lVelIwSEhsb0UKMvw8bZvqRLmetf58Rks05GCJgxVR8wxK
            co5jO7ajK/fauN/hgkIwgEBmmIWgtQWFpUDpSCPTLLa6Wkcg2pskug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ekt5xz7u2xgdzgsrffhd9x22n80cn4thxd8zxjy2ey5vq3ca7gnqz25g5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZUk5TWRYMmVmTXdiOWNB
            TFB1VnZCdHFOTkNETXYzMDJwMkxhYVFVZ0VBCkJzcldWZUl1ZHQxdlRIa1A2ZTYr
            ODFqQys0VThGRDJ1U1k3VnllMi9MajAKLS0tIGU1NWtydnVOMm1pMWRtcEt2MDFI
            NUMyajJZanB0TWVic2hReG8xNmRaS0UK4uKiwktTtToyJBcppVyR4RS8CtY5ouu7
            OYWZrzxKG19Mz9DmT+wFTeKwIMl6bWs3aBQ9pBm6lvCnNea1uefNwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jpeh4s553taxkyxhzlshzqjfrtvmmp5lw0hmpgn3mdnmgzku332qe082dl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdWxYUlg1OXVsenBybFNl
            ZWpxWUtPV1VsSWFyK0hrYlhyKzBRRzNzb1V3CkpPdjJXSEVXMUJBSHl2RitReEZC
            Nk9kZWlnR3MzZXlpQk1hMDdhL1g5Q0kKLS0tIDZNcmE5MWczcEZ4RTZrWVZ4VUVL
            YU03MStkd3FFSUdRTGlMUVFFS0laa2sKipH66LMOl/YNgFWXQUZQIZSgiyor8GrI
            +C6L+HVHVkNC2m+xgLOS7btUHKLnohRtnPnXBddHWO2KsKVpYJLymw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j2r8mypw44uvqhfs53424h6fu2rkr5m7asl7rl3zn3xzva9m3dcqpa97gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBId2pSaXQ2ZXNkTlBHNGJQ
            UXR0YTVMOEgvNkZWeTc0aHdTMmFQejByRUIwCnJNY3NIRDd4ak9Md1dySlZmeUhu
            Y054QWQ0dHEvakZOTHNZQkJURFpRSTAKLS0tIGllWEFBM2VwVFdBd1QyRXdBb0NO
            NEtCNGY0S1JDbU41MmRpbktWVWFUdDgK04+s23eglE4ZShufWxCf+QHh/GXQpOwZ
            PZatWxfyXP4XOkHqmHfbpPdCk5SmrFXUhBdGrEb8DKtvGJQb9yr2xg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezmtw7qaw93yggtcncqpyej9qjlref8au5uceqat49htmlfgps2swsttyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVDJQUE5kdXc0LzhjSTlo
            aWRVUXNwVVBkclp4TnpCcVBVTU01a3dwYjE4Ck5laHp3YUdBM1Y4b2o0ZGpQYWxT
            L2c1OHBXd0xDWjdNQ0lKRlVDK3RobmMKLS0tIFBLdkRtRHpHVDNvR0Y0TFhjTStm
            SXAvcDMvbElkZk9qNWpEYnhnY1FpbEUK4spdEIdizM3iF2np/rK1ntjmJm76Z/ca
            jiLughmS5upu4QXgw3rJ6JDV5H+e4Vehun9PIZnjvqglipu0kXr2QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T08:12:19Z"
    mac: ENC[AES256_GCM,data:Xu5ZtaxStCEStJN76D5FfJcJW+9iG56+ysVuQMwWmZN0SV1kOWZYtEcF+aHHQaBj4MVVQqzRpoAlomNY2DLw6ZbwuHuhdBrZW4zxA9mXdU+A1OhIg8rxGbPhSsGYSBIQjMh6ZF6feu5E8D0LD1rRqDYLsv3fBpFiHyxFs6qLTAs=,iv:OghEo7h/GnKymQK1/nUtt0ddgz4JK8DYxb4Z4yVhYvY=,tag:thXKols0Q0ZuQcdP/9aEHg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
