services:
    restic:
        password: ENC[AES256_GCM,data:vU7hu6JE2Vk=,iv:aLsr3o+9f4PLne1aZqfKl310zbwBoviZx1X7at+Mha0=,tag:JaQm7raE1WQqTpZLFqWI1Q==,type:str]
        repository: ENC[AES256_GCM,data:XAFzJKed9BcnWD2Z89Sf+bcu6Y3vljthwNatRMPaNHk3Op5Yrm7Y1d5CBCnnwJiKus1Tbh/ArY7oiuX+xXnJYlHlH7Rl9Xh8UQwYKa2A+uu/,iv:ChHyWiV0Sah2rR73i20piJ3CmMzTAomECmdCY4FQ3pg=,tag:b+pPaniqVh8xlgAvLcBc8Q==,type:str]
        env: ENC[AES256_GCM,data:7QQP2iqoARjslaEEc31t1rELBpK0U8RMv8DI3+ByxAwUVJKHFxqhdX4uPX1zHMbuEvz2QcaGlaPNcw7Mk5PxyjUZZVaIXU9YLBudLTdVOhdPU6cn44nF6Csh2TAP7uq3fA==,iv:CqDCkREy97XmsCC3oQBtqy2Gv4PfiOWqU6hgw+WzWgw=,tag:Hd9fbtJty0lBP69Q/3r23g==,type:str]
sops:
    age:
        - recipient: age1lj5vmr02qkudvv2xedfj5tq8x93gllgpr6tzylwdlt7lud4tfv5qfqsd5u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bytXZnlOUXJiN013QTM2
            Y3NPSFg5c2gwRi95UFcvT3J5cnlsSjNIdlNFCmV6NlVxVHBhWVFNa3lnTzFPOGpK
            SXVQSWRpdlc3Y0lxdXhBUGJrMjlTK0kKLS0tIDdLTlNxWU9GRENpczRVREVhcjhT
            N0tDUzZIejFxWHR2OHhvQjhDeUs3TE0KNcljHa8fNZTpN0K7/Vrt0TU4JYBgMqdA
            8viycJdVRlHR1QdPadKxyiwIpLcWCcbmkohhSJR/aSri5R4AxVZ68w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17edew3aahg3t5nte5g0a505sn96vnj8g8gqse8q06ccrrn2n3uysyshu2c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4djBwMWZLYlZIRVdDRzlK
            NkJISEx6aG5XdVQvY0J2d2VPZGNCZUpQTEc0CklvcElVTTZIUUxXWFV3bURHM1VH
            ZnJGQlJjTlg5bFQyd1A4OEhhWjhzQjAKLS0tIFJUSXgra3VIa0ZyVTNqNVJjRDZK
            d3AyTzBONUNBQVIvTWVnRnVpN2JvNTgKTp2Y65g8MkTOnPLFQFcE/pj09f+8NVb/
            LabJA16o3OlUJ0RFndz8g3MDBhTteRLPH2mdkye2LcBSXSnoUp745g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rpkr0le4ff550wgyazssfe8r335gjwpyflqezz7trtrhw6ygge3qgydv3y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYzJZMVBmYUtMK3MzNVFj
            ZThuNnNlM2ZkTGVjazZ3VEpuMUFlSGlnblZZCnZHbEMxdlp4emU2TUJhR0NBV3ky
            anl3UG92QWlMSkEwZVVQYUQ5SWpKYk0KLS0tIEtIYThVcjI2WTEydEpaNDNrMWo2
            eVROMFVVWVZ1WUhYdDZpamMxVXNPdE0KuMIx8kH03966mV8l4PF6TLEw2ou3ZGqj
            nrbvfD6SyHT5wkg96VpvFoe00iQqDIdBWmrO0YNQc3pugPg0ilftqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cp6vegrmqfkuj8nmt2u3z0sur7n0f7e9x9zmdv4zygp8j2pnucpsdkgagc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RnMyRlp4VEIvSUFBRUIv
            amRwRDJDbXBISGVUTFdlbmtCL1NHdHRNTG1VCk5OaUZoNUUwSUFSNThtTU9pMTQv
            ZTI2dmRiT09BaG5abFNtZUFQb3ZCWnMKLS0tIEJ6cDF4WkdROTRGQVJDVnVvQnZa
            SDBEZFZDeXA3bUswYWtZUUhzd3haOEEKnRvDXwTVXicBbRrWZBq0yZeuPuTizBVK
            8iF8ljDum/c952nLSpvAhxhKis2DUVtMsymGQGJ83AMg1JaHdhYKFQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ekt5xz7u2xgdzgsrffhd9x22n80cn4thxd8zxjy2ey5vq3ca7gnqz25g5r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZFVGQmUyTHVKZjJGd3lq
            MVVPNWVqMktYVXdOT0M3VjNLUGVqN2pSVmlNCm9FOEpiQm5Cd2NQS3JjZE9XUjM1
            anBtVEpHZlhSN0QwTXQyMmtXUFJPK2MKLS0tIERYSjNXTmMwcHo4MXNiMEZVL1BN
            M0VhNktDNnJ0dWt0aTY5NUY4VDVDZmcKyeT0o7sdBKteR1f/TUSxHj9+vlL6UYPn
            T7wqJLKGVw9FDPOqvqynERzSBYokfkjENu8bnDsMKkPz3AmKLDvNYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mmdjc4qk20accal4p4yhm5d2nsnlfnmmn484pg4mqtsu70fqvy4s6namra
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeFQwQnVVNXZhVlVEQUpC
            Tk1QL08xM2pGOEJUUTB4NlVnbkJad2F1MkVrCm14UHVQQTFuMEwzN1V1VlMzVjd1
            UnNiaDVKdGVZS0VUZUt4SHp6MG1QUHMKLS0tIG0rWG9oeEgyZ2hNYWhwcDF3Kzlj
            UzFGM1EzYUFtZi80aVhvRmpKaTNLYkEKDEv6L2uMPkV/yC1HeVgmaliCmirJI4OT
            lSXiF+1z42OpInEdcyYIesp/xw1UUj/pv7KJp5sIM4UdG8fBLhNAig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1j2r8mypw44uvqhfs53424h6fu2rkr5m7asl7rl3zn3xzva9m3dcqpa97gw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTHJTdnBRZlcyNk1QTTVq
            WE1jazkrZjJLYzQvaUpmSmlaUk1QdjdFRFFzCnA3Zkx5YzY2VFhCMFBUMmRrdzNm
            RGFqK2ZWUWViQm4vMFlhNkhySFVKcGMKLS0tIDBnckdnR3ludm42Wk8zRzkwZndR
            eWsrQ3VtQ0Y0WCs2VzBRWm45WVRMeUEKuIFy1oVZfZNPfmUql1BAhfiEZ84luV7P
            X8/tcdZ5+aMEOACNSxfJygUWxzAP4wSMmuOVnxp5lPbaCes6zFuOyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ezmtw7qaw93yggtcncqpyej9qjlref8au5uceqat49htmlfgps2swsttyr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVCtiM2VHM2tYWjBENlJv
            ekhQOFZWOEUxbVlyZmlwRVdlbWk4cnRTekdBCng0N1RScWtXbE51SEhvUEZ3aDgw
            TWdHNERpSWU0YXkwMXQ3WFIxb3hpem8KLS0tIHQwdXVTT0xjM2lMTnFSNXFIdCtt
            alBBSjZiQmxvYmNnMmhjdUFBSG9Db00KtZSO5/MbNDi2RCP4YgU7lKkv1kc7Yyhn
            Tl/Y4jbwyKnGgV15/vLcj7Bh98/xvz+QFqkazxLHKWy8XKPRGmdJYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1m24gvg0wq5ps872ezcjwdx7e9rrs65rq2vt05qwt9purptxyyessasckk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbHlaQkdQUWMwdVIwL295
            TDNITC9mNDY0Yy9SQWJITm55QzFjeU5pM0JjClVuVnVUQWc2MzM1TU1NbmFpRDkr
            U3NvN1FPL2VwbVJ1ZlBuTXJJWGhaYXcKLS0tIFRDT2tlOUFwbGhUd1VTQzZ2VlJD
            aXZ0d2FVWU85L21ieFo2emxTb3V6ZmMKV+UeLT+ztS0f2+XIkFRD8YvSdj8kaBBM
            RoP12lOUgLVckBSgG4+1Sw0POM/AUx6TELdcIOQEVxIGtBJoSLdeog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13dmfusa7kvgmc9xqzu55ws07y6etzcxa5cx58vkthdaeyuv32ecq3c624g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ2lldHlna2VoR25COXhN
            cWhSbGRIUDgxb1BoRk9qUmMxbXF5cEhyRmdRCmFqRXdWNVVtUERjaGd2akRudnh1
            S3hLL0duRC94S0ZEMWhPRllBMWViT1EKLS0tIHRsOXE4NXQzbG9EbmorMXJJV0lL
            Q1NLbG43V2Z4Rm50eWw4SUNvdEJTMWMKKhf5Cta0XqBhIKoM0LEVtahYaxx6//An
            240FWNNiFFrb+NjBtNQNI5dbyhM9bAnm7CkDnKsl95DG7RKxc8p7YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-30T04:48:42Z"
    mac: ENC[AES256_GCM,data:qGcuiuAHiWm4nS6TKjEFZ4/iDLcSeqDgROpdS8YwRz2UmQyHL9PbHjybldrAIBqQb7GgSunzck9AmmCDTpl61DJXp0lMO6QaPcLVV3MyE1r/PnaPjTFGJs0IVsz69CFnsXwqpTz1HM8/7CGE6lka84KO37FUpHkFrmBsD57rGy4=,iv:n7eOgllkoZ6phgVwZJC3s31K6NLzB2EIudXQj9ljJr4=,tag:8r8zjSPRxWyt7ohLpCHhAA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
