name: update-flake-lock
on:
  workflow_dispatch:          # manual trigger
  schedule:
    - cron: '13 4 * * 1'      # 04:13 UTC every Monday (≈ 14:13 AEST)

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # push the new lock file
      pull-requests: write    # open / merge the PR
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/update-flake-lock@v20
        with:
          # Optional: open a PR instead of direct push
          pr-title: "chore: update flake.lock"
          pr-labels: dependencies,nix
          # Optional: auto-merge if CI passes (needs extra token)
          # auto-merge: true
