name: update-flake-lock
on:
  workflow_dispatch:          # manual trigger
  schedule:
    - cron: '13 4 * * 1'      # 04:13 UTC every Monday (≈ 14:13 AEST)

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # push the new lock file
      pull-requests: write    # open / merge the PR
    steps:
      - name: Generate Github App Token
        uses: navikt/github-app-token-generator@v1
        id: github-app-token
        with:
          app-id: ${{ secrets.TRUXNELL_APP_ID }}
          private-key: ${{ secrets.TRUXNELL_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        id: update-flake-lock
        with:
          commit-msg: "chore: Update flake.lock"
          pr-title: "Update flake.lock"
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          pr-labels: |
            automated
      - run: "gh pr merge --auto --rebase --delete-branch ${{ steps.update-flake-lock.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ github.token }}